export const STATUS_NONE = '__';
export const STATUS_UNSTARTED = 'Unstarted';
export const STATUS_INPROGRES = 'In Progress';
export const STATUS_COMPLETED = 'Completed';

export const TASK_STATUSES = [ STATUS_UNSTARTED, STATUS_INPROGRES, STATUS_COMPLETED ];

//Actions

export const ACTION_FETCH_TASKS = 'ACTION_FETCH_TASKS';
export const ACTION_FETCH_TASKS_OK = 'ACTION_FETCH_TASKS_OK';
export const ACTION_TASK_ERROR = 'ACTION_TASK_ERROR';

export const ACTION_CREATE_TASK = 'ACTION_CREATE_TASK';
export const ACTION_CREATE_TASK_OK = 'ACTION_CREATE_TASK_OK';
export const ACTION_CREATE_ERROR = 'RECEIVE_CREATE_ERROR';

export const ACTION_SET_TASK_STATUS = 'ACTION_SET_TASK_STATUS';
export const ACTION_SET_TASK_OK = 'ACTION_UPDATE_TASKS_OK';
export const ACTION_SET_TASK_ERROR = 'RECEIVE_UPDATE_ERROR';

export const ACTION_REMOVE_TASK = 'ACTION_REMOVE_TASK';
export const ACTION_REMOVE_TASK_OK = 'ACTION_REMOVE_TASK_OK';
export const ACTION_REMOVE_TASK_ERROR = 'ACTION_REMOVE_TASK_ERROR';